version: '3'
services:
  postgres:
    build:
      context: ./database
      dockerfile: postgres.dockerfile
    ports:
      - "5432:5432"
  volumes:
      - ./database:/docker-entrypoint-initdb.d
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres
  backend:
    build:
      context: ./server
      dockerfile: backend.dockerfile
    ports:
      - "3001:3001"
    depends_on:
      - postgres
