version: '3'
services:
  postgres:
    build:
      context: ./database
      dockerfile: dockerfile-postgres.docker
    ports:
      - "5432:5432"
  volumes:
      - ./database:/docker-entrypoint-initdb.d
  backend:
    build:
      context: ./server
      dockerfile: dockerfile-backend.docker
    ports:
      - "3001:3001"
    depends_on:
      - postgres
